// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251122103016_Alter_Table_Puntos_Control")]
    partial class Alter_Table_Puntos_Control
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Authentication.RefreshTokens.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_expiracion");

                    b.Property<DateTime?>("FechaRevocacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_revocacion");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("text")
                        .HasColumnName("replaced_by_token");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_refresh_tokens_usuario_id");

                    b.ToTable("refresh_tokens", "public");
                });

            modelBuilder.Entity("Domain.Dispositivos.Dispositivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mac_address");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("password");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usuario");

                    b.HasKey("Id")
                        .HasName("pk_dispositivos");

                    b.HasIndex("MacAddress")
                        .IsUnique()
                        .HasDatabaseName("ix_dispositivos_mac_address");

                    b.ToTable("dispositivos", "public");
                });

            modelBuilder.Entity("Domain.Parametros.Parametro", b =>
                {
                    b.Property<string>("Llave")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("llave");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("valor");

                    b.HasKey("Llave")
                        .HasName("pk_parametros");

                    b.ToTable("parametros", "public");
                });

            modelBuilder.Entity("Domain.Permisos.Permiso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_permisos");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_permisos_nombre");

                    b.ToTable("permisos", "public");
                });

            modelBuilder.Entity("Domain.PuntosControl.PuntoControl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion");

                    b.Property<string>("DispositivoLectorQr")
                        .HasColumnType("jsonb")
                        .HasColumnName("dispositivo_lector_qr");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ubicacion");

                    b.HasKey("Id")
                        .HasName("pk_puntos_control");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_puntos_control_nombre");

                    b.ToTable("puntos_control", "public");
                });

            modelBuilder.Entity("Domain.RegistrosIngresosEgresos.RegistroIngresoEgreso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_hora");

                    b.Property<Guid>("IdPuntoEntrada")
                        .HasColumnType("uuid")
                        .HasColumnName("id_punto_entrada");

                    b.Property<Guid>("IdPuntoSalida")
                        .HasColumnType("uuid")
                        .HasColumnName("id_punto_salida");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("resultado");

                    b.HasKey("Id")
                        .HasName("pk_registros_ingresos_egresos");

                    b.HasIndex("IdPuntoEntrada")
                        .HasDatabaseName("ix_registros_ingresos_egresos_id_punto_entrada");

                    b.HasIndex("IdPuntoSalida")
                        .HasDatabaseName("ix_registros_ingresos_egresos_id_punto_salida");

                    b.ToTable("registros_ingresos_egresos", "public");
                });

            modelBuilder.Entity("Domain.Roles.Rol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("descripcion");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre_rol");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("NombreRol")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_nombre_rol");

                    b.ToTable("roles", "public");
                });

            modelBuilder.Entity("Domain.RolesPermisos.RolPermiso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("PermisoId")
                        .HasColumnType("uuid")
                        .HasColumnName("permiso_id");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uuid")
                        .HasColumnName("rol_id");

                    b.HasKey("Id")
                        .HasName("pk_roles_permisos");

                    b.HasIndex("PermisoId")
                        .HasDatabaseName("ix_roles_permisos_permiso_id");

                    b.HasIndex("RolId", "PermisoId")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_permisos_rol_id_permiso_id");

                    b.ToTable("roles_permisos", "public");
                });

            modelBuilder.Entity("Domain.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("apellido");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<DateTime>("FechaUltimaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_ultima_modificacion");

                    b.Property<TimeSpan>("HorarioFin")
                        .HasColumnType("time")
                        .HasColumnName("horario_fin");

                    b.Property<TimeSpan>("HorarioInicio")
                        .HasColumnType("time")
                        .HasColumnName("horario_inicio");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numero_documento");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_email");

                    b.HasIndex("NumeroDocumento")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_numero_documento");

                    b.ToTable("usuarios", "public");
                });

            modelBuilder.Entity("Domain.UsuariosRoles.UsuarioRol", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uuid")
                        .HasColumnName("rol_id");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_asignacion");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.HasKey("UsuarioId", "RolId")
                        .HasName("pk_usuarios_roles");

                    b.HasIndex("RolId")
                        .HasDatabaseName("ix_usuarios_roles_rol_id");

                    b.HasIndex("UsuarioId")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_roles_usuario_id");

                    b.ToTable("usuarios_roles", "public");
                });

            modelBuilder.Entity("Domain.ZonasEstacionamiento.ZonaEstacionamiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CapacidadMaxima")
                        .HasColumnType("integer")
                        .HasColumnName("capacidad_maxima");

                    b.Property<int>("EspaciosUtilizados")
                        .HasColumnType("integer")
                        .HasColumnName("espacios_utilizados");

                    b.Property<Guid>("IdPuntoAsociado")
                        .HasColumnType("uuid")
                        .HasColumnName("id_punto_asociado");

                    b.Property<string>("NombreZona")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre_zona");

                    b.HasKey("Id")
                        .HasName("pk_zonas_estacionamiento");

                    b.HasIndex("IdPuntoAsociado")
                        .HasDatabaseName("ix_zonas_estacionamiento_id_punto_asociado");

                    b.ToTable("zonas_estacionamiento", "public");
                });

            modelBuilder.Entity("Domain.Authentication.RefreshTokens.RefreshToken", b =>
                {
                    b.HasOne("Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_usuarios_usuario_id");
                });

            modelBuilder.Entity("Domain.RegistrosIngresosEgresos.RegistroIngresoEgreso", b =>
                {
                    b.HasOne("Domain.PuntosControl.PuntoControl", null)
                        .WithMany()
                        .HasForeignKey("IdPuntoEntrada")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_registros_ingresos_egresos_puntos_control_id_punto_entrada");

                    b.HasOne("Domain.PuntosControl.PuntoControl", null)
                        .WithMany()
                        .HasForeignKey("IdPuntoSalida")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_registros_ingresos_egresos_puntos_control_id_punto_salida");
                });

            modelBuilder.Entity("Domain.RolesPermisos.RolPermiso", b =>
                {
                    b.HasOne("Domain.Permisos.Permiso", null)
                        .WithMany()
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_roles_permisos_permisos_permiso_id");

                    b.HasOne("Domain.Roles.Rol", null)
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_roles_permisos_roles_rol_id");
                });

            modelBuilder.Entity("Domain.UsuariosRoles.UsuarioRol", b =>
                {
                    b.HasOne("Domain.Roles.Rol", null)
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_roles_roles_rol_id");

                    b.HasOne("Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_roles_usuarios_usuario_id");
                });

            modelBuilder.Entity("Domain.ZonasEstacionamiento.ZonaEstacionamiento", b =>
                {
                    b.HasOne("Domain.PuntosControl.PuntoControl", null)
                        .WithMany()
                        .HasForeignKey("IdPuntoAsociado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_zonas_estacionamiento_puntos_control_id_punto_asociado");
                });
#pragma warning restore 612, 618
        }
    }
}
