// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260112014006_Add_table_ZonasPuntosControl")]
    partial class Add_table_ZonasPuntosControl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Authentication.RefreshTokens.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_expiracion");

                    b.Property<DateTime?>("FechaRevocacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_revocacion");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("text")
                        .HasColumnName("replaced_by_token");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_refresh_tokens_usuario_id");

                    b.ToTable("refresh_tokens", "public");
                });

            modelBuilder.Entity("Domain.Dispositivos.Dispositivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<string>("DireccionIp")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("direccion_ip");

                    b.Property<string>("DispositivoId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("dispositivo_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo");

                    b.Property<DateTime?>("UltimaConexion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_conexion");

                    b.Property<string>("VersionFirmware")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("version_firmware");

                    b.HasKey("Id")
                        .HasName("pk_dispositivos");

                    b.HasIndex("DireccionIp")
                        .IsUnique()
                        .HasDatabaseName("ix_dispositivos_direccion_ip");

                    b.HasIndex("DispositivoId")
                        .IsUnique()
                        .HasDatabaseName("ix_dispositivos_dispositivo_id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_dispositivos_nombre");

                    b.ToTable("dispositivos", "public");
                });

            modelBuilder.Entity("Domain.Dispositivos.DispositivoConfiguracion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CanalComunicacion")
                        .HasColumnType("integer")
                        .HasColumnName("canal_comunicacion");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<Guid>("DispositivoId")
                        .HasColumnType("uuid")
                        .HasColumnName("dispositivo_id");

                    b.Property<int>("FrecuenciaSincronizacionSegundos")
                        .HasColumnType("integer")
                        .HasColumnName("frecuencia_sincronizacion_segundos");

                    b.Property<string>("PotenciaTransmision")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("potencia_transmision");

                    b.HasKey("Id")
                        .HasName("pk_dispositivo_configuraciones");

                    b.HasIndex("DispositivoId")
                        .IsUnique()
                        .HasDatabaseName("ix_dispositivo_configuraciones_dispositivo_id");

                    b.ToTable("dispositivo_configuraciones", "public");
                });

            modelBuilder.Entity("Domain.EstadosRegistro.EstadoRegistro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AfectaEspacio")
                        .HasColumnType("boolean")
                        .HasColumnName("afecta_espacio");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descripcion");

                    b.HasKey("Id")
                        .HasName("pk_estados_registro");

                    b.HasIndex("Descripcion")
                        .IsUnique()
                        .HasDatabaseName("ix_estados_registro_descripcion");

                    b.ToTable("estados_registro", "public");
                });

            modelBuilder.Entity("Domain.Parametros.Parametro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActualizadoPor")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("actualizado_por");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<string>("Llave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("llave");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("valor");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_parametros");

                    b.HasIndex("Llave")
                        .IsUnique()
                        .HasDatabaseName("ix_parametros_llave");

                    b.ToTable("parametros", "public");
                });

            modelBuilder.Entity("Domain.Parametros.ParametroHistorial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActualizadoPor")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("actualizado_por");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<string>("Llave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("llave");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("valor");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_parametros_historial");

                    b.HasIndex("FechaActualizacion")
                        .HasDatabaseName("ix_parametros_historial_fecha_actualizacion");

                    b.HasIndex("Llave")
                        .HasDatabaseName("ix_parametros_historial_llave");

                    b.HasIndex("Llave", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_parametros_historial_llave_version");

                    b.ToTable("parametros_historial", "public");
                });

            modelBuilder.Entity("Domain.Parametros.ParametroSchema", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Llave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("llave");

                    b.Property<string>("Schema")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("schema");

                    b.HasKey("Id")
                        .HasName("pk_parametro_schemas");

                    b.ToTable("parametro_schemas", "public");
                });

            modelBuilder.Entity("Domain.Permisos.Permiso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_permisos");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_permisos_nombre");

                    b.ToTable("permisos", "public");
                });

            modelBuilder.Entity("Domain.PuntosControl.PuntoControl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion");

                    b.Property<string>("DispositivoLectorQr")
                        .HasColumnType("jsonb")
                        .HasColumnName("dispositivo_lector_qr");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ubicacion");

                    b.HasKey("Id")
                        .HasName("pk_puntos_control");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_puntos_control_nombre");

                    b.ToTable("puntos_control", "public");
                });

            modelBuilder.Entity("Domain.QrTokens.QrToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<Guid?>("DispositivoId")
                        .HasColumnType("uuid")
                        .HasColumnName("dispositivo_id");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_expiracion");

                    b.Property<DateTime?>("FechaUso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_uso");

                    b.Property<Guid?>("PuntoControlId")
                        .HasColumnType("uuid")
                        .HasColumnName("punto_control_id");

                    b.Property<Guid?>("RegistroIngresoId")
                        .HasColumnType("uuid")
                        .HasColumnName("registro_ingreso_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("token");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<Guid?>("ZonaId")
                        .HasColumnType("uuid")
                        .HasColumnName("zona_id");

                    b.HasKey("Id")
                        .HasName("pk_qr_tokens");

                    b.HasIndex("DispositivoId")
                        .HasDatabaseName("ix_qr_tokens_dispositivo_id");

                    b.HasIndex("PuntoControlId")
                        .HasDatabaseName("ix_qr_tokens_punto_control_id");

                    b.HasIndex("RegistroIngresoId")
                        .HasDatabaseName("ix_qr_tokens_registro_ingreso_id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_qr_tokens_token");

                    b.HasIndex("ZonaId")
                        .HasDatabaseName("ix_qr_tokens_zona_id");

                    b.ToTable("qr_tokens", "public");
                });

            modelBuilder.Entity("Domain.RegistrosIngresosEgresos.RegistroIngresoEgreso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<Guid>("EstadoRegistroId")
                        .HasColumnType("uuid")
                        .HasColumnName("estado_registro_id");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<Guid?>("PuntoEntradaId")
                        .HasColumnType("uuid")
                        .HasColumnName("punto_entrada_id");

                    b.Property<Guid?>("PuntoSalidaId")
                        .HasColumnType("uuid")
                        .HasColumnName("punto_salida_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<Guid>("ZonaRolId")
                        .HasColumnType("uuid")
                        .HasColumnName("zona_rol_id");

                    b.HasKey("Id")
                        .HasName("pk_registros_ingresos_egresos");

                    b.HasIndex("EstadoRegistroId")
                        .HasDatabaseName("ix_registros_ingresos_egresos_estado_registro_id");

                    b.HasIndex("PuntoEntradaId")
                        .HasDatabaseName("ix_registros_ingresos_egresos_punto_entrada_id");

                    b.HasIndex("PuntoSalidaId")
                        .HasDatabaseName("ix_registros_ingresos_egresos_punto_salida_id");

                    b.HasIndex("ZonaRolId")
                        .HasDatabaseName("ix_registros_ingresos_egresos_zona_rol_id");

                    b.ToTable("registros_ingresos_egresos", "public");
                });

            modelBuilder.Entity("Domain.Roles.Rol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("EsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("es_admin");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre_rol");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("NombreRol")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_nombre_rol");

                    b.ToTable("roles", "public");
                });

            modelBuilder.Entity("Domain.RolesPermisos.RolPermiso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<Guid>("PermisoId")
                        .HasColumnType("uuid")
                        .HasColumnName("permiso_id");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uuid")
                        .HasColumnName("rol_id");

                    b.HasKey("Id")
                        .HasName("pk_roles_permisos");

                    b.HasIndex("PermisoId")
                        .HasDatabaseName("ix_roles_permisos_permiso_id");

                    b.HasIndex("RolId", "PermisoId")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_permisos_rol_id_permiso_id");

                    b.ToTable("roles_permisos", "public");
                });

            modelBuilder.Entity("Domain.RolesUI.RolUI", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasDefaultValue("#FFFFFF")
                        .HasColumnName("background_color");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uuid")
                        .HasColumnName("rol_id");

                    b.Property<string>("TextColor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasDefaultValue("#000000")
                        .HasColumnName("text_color");

                    b.HasKey("Id")
                        .HasName("pk_roles_ui");

                    b.HasIndex("RolId")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_ui_rol_id");

                    b.ToTable("roles_ui", "public");
                });

            modelBuilder.Entity("Domain.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("apellido");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<string>("FcmToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("fcm_token");

                    b.Property<DateTime?>("FcmTokenUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fcm_token_updated_at");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<DateTime>("FechaUltimaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_ultima_modificacion");

                    b.Property<TimeSpan>("HorarioFin")
                        .HasColumnType("time")
                        .HasColumnName("horario_fin");

                    b.Property<TimeSpan>("HorarioInicio")
                        .HasColumnType("time")
                        .HasColumnName("horario_inicio");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numero_documento");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_email");

                    b.HasIndex("NumeroDocumento")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_numero_documento");

                    b.ToTable("usuarios", "public");
                });

            modelBuilder.Entity("Domain.UsuariosRoles.UsuarioRol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_asignacion");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uuid")
                        .HasColumnName("rol_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_usuarios_roles");

                    b.HasIndex("RolId")
                        .HasDatabaseName("ix_usuarios_roles_rol_id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_usuarios_roles_usuario_id");

                    b.HasIndex("UsuarioId", "RolId")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_roles_usuario_id_rol_id");

                    b.ToTable("usuarios_roles", "public");
                });

            modelBuilder.Entity("Domain.Zonas.Zona", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_zonas");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_zonas_nombre");

                    b.ToTable("zonas", "public");
                });

            modelBuilder.Entity("Domain.ZonasPuntosControl.ZonaPuntoControl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<Guid>("PuntoControlId")
                        .HasColumnType("uuid")
                        .HasColumnName("punto_control_id");

                    b.Property<Guid>("ZonaId")
                        .HasColumnType("uuid")
                        .HasColumnName("zona_id");

                    b.HasKey("Id")
                        .HasName("pk_zonas_puntos_control");

                    b.HasIndex("ZonaId", "PuntoControlId")
                        .IsUnique()
                        .HasDatabaseName("ix_zonas_puntos_control_zona_id_punto_control_id");

                    b.ToTable("zonas_puntos_control", "public");
                });

            modelBuilder.Entity("Domain.ZonasRoles.ZonaRol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CapacidadMaxima")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("capacidad_maxima");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<int>("EspacioUtilizado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("espacio_utilizado");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uuid")
                        .HasColumnName("rol_id");

                    b.Property<Guid>("ZonaId")
                        .HasColumnType("uuid")
                        .HasColumnName("zona_id");

                    b.HasKey("Id")
                        .HasName("pk_zonas_roles");

                    b.HasIndex("ZonaId", "RolId")
                        .IsUnique()
                        .HasDatabaseName("ix_zonas_roles_zona_id_rol_id");

                    b.ToTable("zonas_roles", "public");
                });

            modelBuilder.Entity("Domain.Authentication.RefreshTokens.RefreshToken", b =>
                {
                    b.HasOne("Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_usuarios_usuario_id");
                });

            modelBuilder.Entity("Domain.Dispositivos.DispositivoConfiguracion", b =>
                {
                    b.HasOne("Domain.Dispositivos.Dispositivo", null)
                        .WithOne()
                        .HasForeignKey("Domain.Dispositivos.DispositivoConfiguracion", "DispositivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dispositivo_configuraciones_dispositivos_dispositivo_id");
                });

            modelBuilder.Entity("Domain.QrTokens.QrToken", b =>
                {
                    b.HasOne("Domain.Dispositivos.Dispositivo", null)
                        .WithMany()
                        .HasForeignKey("DispositivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_qr_tokens_dispositivos_dispositivo_id");

                    b.HasOne("Domain.PuntosControl.PuntoControl", null)
                        .WithMany()
                        .HasForeignKey("PuntoControlId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_qr_tokens_puntos_control_punto_control_id");

                    b.HasOne("Domain.RegistrosIngresosEgresos.RegistroIngresoEgreso", null)
                        .WithMany()
                        .HasForeignKey("RegistroIngresoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_qr_tokens_registros_ingresos_egresos_registro_ingreso_id");

                    b.HasOne("Domain.Zonas.Zona", null)
                        .WithMany()
                        .HasForeignKey("ZonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_qr_tokens_zonas_zona_id");
                });

            modelBuilder.Entity("Domain.RegistrosIngresosEgresos.RegistroIngresoEgreso", b =>
                {
                    b.HasOne("Domain.EstadosRegistro.EstadoRegistro", null)
                        .WithMany()
                        .HasForeignKey("EstadoRegistroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_registros_ingresos_egresos_estados_registro_estado_registro");

                    b.HasOne("Domain.PuntosControl.PuntoControl", null)
                        .WithMany()
                        .HasForeignKey("PuntoEntradaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_registros_ingresos_egresos_puntos_control_punto_entrada_id");

                    b.HasOne("Domain.PuntosControl.PuntoControl", null)
                        .WithMany()
                        .HasForeignKey("PuntoSalidaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_registros_ingresos_egresos_puntos_control_punto_salida_id");

                    b.HasOne("Domain.ZonasRoles.ZonaRol", null)
                        .WithMany()
                        .HasForeignKey("ZonaRolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_registros_ingresos_egresos_zonas_roles_zona_rol_id");
                });

            modelBuilder.Entity("Domain.RolesPermisos.RolPermiso", b =>
                {
                    b.HasOne("Domain.Permisos.Permiso", null)
                        .WithMany()
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_roles_permisos_permisos_permiso_id");

                    b.HasOne("Domain.Roles.Rol", null)
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_roles_permisos_roles_rol_id");
                });

            modelBuilder.Entity("Domain.UsuariosRoles.UsuarioRol", b =>
                {
                    b.HasOne("Domain.Roles.Rol", null)
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_roles_roles_rol_id");

                    b.HasOne("Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_roles_usuarios_usuario_id");
                });
#pragma warning restore 612, 618
        }
    }
}
