// <auto-generated />
using System;
using Infrastructure.Analytics;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Analytics.Migrations
{
    [DbContext(typeof(AnalyticDbContext))]
    [Migration("20251130014140_Add_Table_Accesos_Por_Hora")]
    partial class Add_Table_Accesos_Por_Hora
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Analytics.AccesosPorHora.AccesoPorHora", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha");

                    b.Property<int>("Hora")
                        .HasColumnType("integer")
                        .HasColumnName("hora");

                    b.HasKey("Id")
                        .HasName("pk_accesos_por_hora");

                    b.HasIndex("Fecha", "Hora")
                        .IsUnique()
                        .HasDatabaseName("ix_accesos_por_hora_fecha_hora");

                    b.ToTable("accesos_por_hora", "public");
                });

            modelBuilder.Entity("Domain.Analytics.AccesosTipoUsuario.AccesoTipoUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo_usuario");

                    b.HasKey("Id")
                        .HasName("pk_accesos_tipo_usuario");

                    b.ToTable("accesos_tipo_usuario", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
