// <auto-generated />
using System;
using Infrastructure.Analytics;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Analytics.Migrations
{
    [DbContext(typeof(AnalyticDbContext))]
    partial class AnalyticDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Analytics.AccesosDiaSemana.AccesoDiaSemana", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<string>("DiaSemanaCompleto")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("dia_semana_completo");

                    b.Property<string>("DiaSemanaCorto")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("dia_semana_corto");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha");

                    b.HasKey("Id")
                        .HasName("pk_accesos_dia_semana");

                    b.HasIndex("Fecha", "DiaSemanaCompleto")
                        .IsUnique()
                        .HasDatabaseName("ix_accesos_dia_semana_fecha_dia_semana_completo");

                    b.ToTable("accesos_dia_semana", "public");
                });

            modelBuilder.Entity("Domain.Analytics.AccesosIncidencias.AccesoIncidencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("Incidencia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("incidencia");

                    b.Property<string>("NombrePuntoControl")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre_punto_control");

                    b.Property<Guid>("PuntoControlId")
                        .HasColumnType("uuid")
                        .HasColumnName("punto_control_id");

                    b.HasKey("Id")
                        .HasName("pk_accesos_incidencias");

                    b.HasIndex("PuntoControlId", "Incidencia", "Fecha")
                        .IsUnique()
                        .HasDatabaseName("ix_accesos_incidencias_punto_control_id_incidencia_fecha");

                    b.ToTable("accesos_incidencias", "public");
                });

            modelBuilder.Entity("Domain.Analytics.AccesosPorHora.AccesoPorHora", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha");

                    b.Property<int>("Hora")
                        .HasColumnType("integer")
                        .HasColumnName("hora");

                    b.HasKey("Id")
                        .HasName("pk_accesos_por_hora");

                    b.HasIndex("Fecha", "Hora")
                        .IsUnique()
                        .HasDatabaseName("ix_accesos_por_hora_fecha_hora");

                    b.ToTable("accesos_por_hora", "public");
                });

            modelBuilder.Entity("Domain.Analytics.AccesosTipoUsuario.AccesoTipoUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo_usuario");

                    b.HasKey("Id")
                        .HasName("pk_accesos_tipo_usuario");

                    b.ToTable("accesos_tipo_usuario", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
